<?php

namespace Koenvu\FormTests\Components;

use PHPUnit_Framework_TestCase;
use Koenvu\Forms\Components\Elementary;
use Koenvu\Forms\Contracts\FormElement;

class LabellerTest extends PHPUnit_Framework_TestCase
{
    public function testEnhanceLabelWithId()
    {
        $field = $this->getMockForAbstractClass('Koenvu\FormTests\Stubs\TestableLabeller');
        $field->set('field.id', 'sampleid');

        $field->enhanceLabels();

        $this->assertEquals('sampleid', $field->get('label.for'));
        $this->assertRegExp('/for\s*=\s*([\'"])sampleid\1/', $field->attr('label.for'));
        $this->assertNotRegExp('/label\.for/', $field->attr('label.for'));
    }

    public function testEnhanceLabelWithAutogeneratedId()
    {
        $field = $this->getMockForAbstractClass('Koenvu\FormTests\Stubs\TestableLabeller');

        $field->enhanceLabels(true);

        $this->assertEquals(spl_object_hash($field), $field->get('label.for'));
    }
}
