<?php

namespace Koenvu\FormTests\Components;

use PHPUnit_Framework_TestCase;
use Koenvu\Forms\Components\Elementary;
use Koenvu\Forms\Contracts\FormElement;

class LabellerTest extends PHPUnit_Framework_TestCase
{
    public function testEnhanceLabelWithId()
    {
        $labeller = $this->getMockForTrait('Koenvu\Forms\Components\Labeller');
        $field = $this->getMockForAbstractClass('Koenvu\FormTests\Stubs\TestableField');
        $field->set('field.id', 'sampleid');

        $labeller->enhanceLabels([$field]);

        $this->assertEquals('sampleid', $field->get('label.for'));
    }

    public function testEnhanceLabelWithAutogeneratedId()
    {
        $labeller = $this->getMockForTrait('Koenvu\Forms\Components\Labeller');
        $field = $this->getMockForAbstractClass('Koenvu\FormTests\Stubs\TestableField');

        $labeller->enhanceLabels([$field], true);

        $this->assertEquals(spl_object_hash($field), $field->get('label.for'));
    }
}
