<?php

use Koenvu\Forms\Contracts\FormElement;
use Koenvu\Forms\Components\Elementary;

class LabellerTest extends PHPUnit_Framework_TestCase
{
    public function testEnhanceLabelWithId()
    {
        $labeller = $this->getMockForTrait('Koenvu\Forms\Components\Labeller');
        $field = $this->getMockForAbstractClass('TestableField');
        $field->set('field.id', 'sampleid');

        $labeller->enhanceLabels([$field]);

        $this->assertEquals('sampleid', $field->get('label.for'));
    }

    public function testEnhanceLabelWithAutogeneratedId()
    {
        $labeller = $this->getMockForTrait('Koenvu\Forms\Components\Labeller');
        $field = $this->getMockForAbstractClass('TestableField');

        $labeller->enhanceLabels([$field], true);

        $this->assertEquals(spl_object_hash($field), $field->get('label.for'));
    }
}
